source 'http://rubygems.org'

gem 'activerecord'
gem 'database_cleaner'
gem 'pry'
gem 'pry-nav'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'thin'
gem 'tux'
gem 'capybara'
